// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_6fcYYHKsg14K21Fscrb6Uly832JHhw',
    appId: '1:686771495616:web:33f17a651b02ab59600325',
    messagingSenderId: '686771495616',
    projectId: 'uff-delivery-69a36',
    authDomain: 'uff-delivery-69a36.firebaseapp.com',
    storageBucket: 'uff-delivery-69a36.firebasestorage.app',
    measurementId: 'G-04KBG2Y7B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDmZddKrnaUGm2T70k2YUOyIt25VEy9KE',
    appId: '1:686771495616:android:13195033e1dd8f65600325',
    messagingSenderId: '686771495616',
    projectId: 'uff-delivery-69a36',
    storageBucket: 'uff-delivery-69a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGePMYfGwAjvkfU2-9ocEcqZlnvW2IM4',
    appId: '1:686771495616:ios:e6c8b5af27f2e502600325',
    messagingSenderId: '686771495616',
    projectId: 'uff-delivery-69a36',
    storageBucket: 'uff-delivery-69a36.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_6fcYYHKsg14K21Fscrb6Uly832JHhw',
    appId: '1:686771495616:web:96e81a9fd34188f3600325',
    messagingSenderId: '686771495616',
    projectId: 'uff-delivery-69a36',
    authDomain: 'uff-delivery-69a36.firebaseapp.com',
    storageBucket: 'uff-delivery-69a36.firebasestorage.app',
    measurementId: 'G-NWR1GGJFXE',
  );
}
